baseURL = 'https://wow2006.github.io/'
languageCode = 'en-us'
title = 'Salt and Pepper'
theme = 'hello-friend-ng'

[params]
  homeSubtitle = "An other Computer Graphics and Vision blog"
  [params.logo]
    logoText = "Home"
    logoHomeLink = "/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blogs"
    url        = "/posts"
  [[menu.main]]
    identifier = "project"
    name       = "Projects"
    url        = "/projects"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"